### ISSUE TITLE
Hacer el punto 6 de la documentación

### ISSUE THREAD

**Issue by diegomarty00** [Arquisoft/dede_es2b#25]
Completar la primera versión del punto 6 de la documentación del proyecto.

Realizar un diagrama por cada miembro del grupo.

**Comment by UO269855** [comment]
Me encargaré de hacer el diagrama de eliminar productos del carrito de compra.

**Comment by UO264268** [comment]
Yo me encargaré de realizar el diagrama de inicio de sesión

**Comment by UO277188** [comment]
Yo haré el diagrama de ver los pedidos realizados.

**Comment by diegomarty00** [comment]
Yo realizaré un diagrama de las ventas realizadas.
