### ISSUE TITLE
Repartición de los puntos de la documentación.

### ISSUE THREAD

**Issue by UO269855** [Arquisoft/dede_es2b#5]
Voy a hacer los puntos 1 y 2 de la documentación, además de los diagramas necesarios para el punto 6. Lo he comentado por el grupo que tenemos y nadie me ha puesto nignuna pega, a si que esos dos puntos los hago yo.

**Comment by UO276840** [comment]
Haré los puntos 3 y 13 de la documentación y los diagramas necesarios del punto 6.

**Comment by UO277188** [comment]
Yo haré el 4 y el 7 y los diagramas necesarios para el 6.

**Comment by UO264268** [comment]
Yo haré los puntos 10 y 11, además de los diagramas necesarios para el punto 6.

**Comment by diegomarty00** [comment]
Yo haré el punto 5 junto con los diagramas necesarios para el punto 6.
